source "http://rubygems.org/"

gem "sinatra"
gem "rdiscount"
gem "dm-core"
gem "dm-serializer"
gem "dm-timestamps"
gem "dm-migrations"
gem "dm-postgres-adapter"
gem "dm-sqlite-adapter"
gem "omniauth"
gem "haml"
